- id: '1704312252710'
  alias: 'Quarto do Edu: Ar-condicionado: Alternar Estado'
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: F97A501A-5110-4BA5-910C-4FD9B6572530
    alias: Quando a ação “Ar-condicionado“ do IOs for acionada
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: climate.quarto_do_edu_ar_condicionado
        state: 'off'
        alias: Se o Ar-condicionado do Quarto do Edu estiver desligado
      sequence:
      - alias: Liga o Ar-condicionado do Quarto do Edu
        service: climate.turn_on
        target:
          entity_id: climate.quarto_do_edu_ar_condicionado
        data: {}
      alias: Liga o Ar-condicionado do Quarto do Edu se ele estiver desligado
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: climate.quarto_do_edu_ar_condicionado
          state: 'off'
        alias: Se o Ar-condicionado do Quarto do Edu não estiver desligado
      sequence:
      - alias: Desliga o Ar-condicionado do Quarto do Edu
        service: climate.turn_off
        target:
          entity_id: climate.quarto_do_edu_ar_condicionado
        data: {}
      alias: Desligar o Ar-condicionado do Quarto do Edu se estiver em qualquer outra
        situação
  mode: single
