id: 'casa_notificar_atividades'
alias: 'Casa: Notificar Atividades'
description: ''
trigger:
- alias: Quando dispositivos selecionados mudarem de estado
  id: casa_notificar_atividades_state_trigger
  platform: state
  entity_id: []
  from:
  to:
- platform: state
  entity_id:
  - cover.frente_portao_da_garagem
  from:
  to:
  id: casa_notificar_atividades_frente_portao_da_garagem_state_trigger
  alias: Quando Portão da Garagem mudar de estado
- id: casa_notificar_atividades_hass_on_trigger
  platform: homeassistant
  event: start
- id: casa_notificar_atividades_hass_off_trigger
  platform: homeassistant
  event: shutdown
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id:  
      - casa_notificar_atividades_state_trigger
    sequence:
    - service: telegram_bot.send_message
      data:
        title: '{{ trigger.from_state.entity_id }}'
        message: '{% from ''translator.jinja'' import format_state %} {{ format_state(trigger.from_state)
          }} ➡️ {{ format_state(trigger.to_state) }}'
    alias: Se dispositivos selecionados mudaram de estado, enviar notificação pelo
      Telegram
  - conditions:
    - condition: trigger
      id:
      - casa_notificar_atividades_hass_off_trigger
    sequence:
    - service: telegram_bot.send_message
      data:
        title: '{{ "Home Assistant" }}'
        message: '{{ "Home Assistant esta Desligando" }}'
  - conditions:
    - condition: trigger
      id:
      - casa_notificar_atividades_hass_on_trigger
    sequence:
    - service: telegram_bot.send_message
      data:
        title: '{{ "Home Assistant 123" }}'
        message: '{{ "Home Assistant esta Ligando" }}'
  - conditions:
    - condition: trigger
      id:
      - casa_notificar_atividades_frente_portao_da_garagem_state_trigger
      alias: Se Portão da Garagem mudou de estado
    sequence:
    - service: camera.record
      target:
        entity_id: camera.frente_camera_da_lateral
      data:
        duration: 10
        filename: /config/www/records/frente_camera_da_garagem.mp4
      alias: Gravar a Câmera da Garagem por 10seg.
    - alias: Enviar o vídeo gravado pela Câmera da Garagem pelo Telegram
      service: telegram_bot.send_video
      data:
        file: /config/www/records/frente_camera_da_garagem.mp4
    alias: Se Portão da Garagem mudou de estado, gravar a Câmera da Garagem por
      10seg. e enviá-lo pelo Telegram
mode: queued
max: 10